"""Provider-free product architecture for the capsule backend.

A capsule backend produces only an untrusted transient workspace and a
`ProviderOutput`; it owns no Git stage, commit, or publication authority.
Acceptance flows exclusively through `CanonicalIntake` (exact bounded file
bytes), `IndependentVerification` (checkpoint and behavioral verification
kept structurally separate), and `AdmissibleFinalizer` (the sole path to an
accepted Git commit).

Historical Cursor/ACP backend code under `admissible.delegated_gate` and
`admissible.v0_controller` is retained as historical Cursor backend support
and protocol-handling defense in depth. It is not the trusted root authority
for this capsule backend architecture; nothing in this package is coupled to
it, and nothing in this package reinterprets its historical run evidence.
"""

from admissible.capsule.backend import CapsuleAuthority, CapsuleBackend, CapsuleTerminalClassification
from admissible.capsule.events import (
    BehaviorVerified,
    CapsuleEvent,
    CapsuleExecutionStarted,
    CheckpointVerificationStarted,
    CheckpointVerified,
    FailureCode,
    FinalizationCompleted,
    FinalizationStarted,
    IntakeEvaluated,
    IntakeStarted,
    ProviderOutputFrozen,
    RefusalReason,
    SessionFailed,
)
from admissible.capsule.finalizer import (
    AcceptedBlob,
    AdmissibleFinalizer,
    DurabilityReceipt,
    DurableEvidenceStoreAuthority,
    DurableFinalizationEvidenceStore,
    FinalizationEvidence,
    FinalizationOutcome,
    FinalizationResult,
    FinalizerAuthority,
    FinalizerOperationalError,
    FinalizerPreconditionError,
    FROZEN_IDENTITY,
    PreparedFinalization,
    initialize_disposable_repository,
)
from admissible.capsule.intake import (
    CANARY_EXACT_AUTHORITY,
    CANARY_TXT_BYTES,
    NEON_RELAY_AUTHORITY,
    AcceptedMaterialIdentity,
    CanonicalIntake,
    ExactMaterialRecord,
    IntakeAuthority,
    IntakeEvidence,
    IntakeFileRecord,
    IntakePublicationState,
    RejectionCode,
    path_policy_reasons,
    validate_and_copy,
)
from admissible.capsule.model_authority import (
    CANARY_ALLOW_PROVIDER_MODEL_FALLBACK,
    CANARY_CONFIGURED_MODEL,
    CANARY_CONFIGURED_REASONING_EFFORT,
    CANARY_PINNED_CODEX_SHA256,
    CANARY_PINNED_CODEX_VERSION,
    CANARY_PROTOCOL_SCHEMA_IDENTITY,
    MODEL_CONFIGURATION_CHANNEL,
    CodexModelAuthority,
    ModelBindingPolicy,
    ModelConfigurationError,
    canary_model_authority,
    canary_model_binding_policy,
    ephemeral_config_bytes,
    validate_effective_thread_configuration,
)
from admissible.capsule.serialization_witness import (
    CANDIDATE_WITNESS_TRUST_STATE,
    SerializationWitnessError,
    SerializationWitnessRecord,
    CandidateEvidenceBundle,
    CandidateSerializationWitnessPack,
    CandidateSerializationWitnessStore,
    CandidateSerializationWitnessReceipt,
    evaluate_serialization_witness,
    extract_witness_record,
    serialization_witness_identity,
    trusted_witness_verifier_identity,
    witness_capture_policy,
)
from admissible.capsule.preflight_seal import (
    FUTURE_PREFLIGHT_MANIFEST_PATH,
    FUTURE_PREFLIGHT_SEAL_PATH,
    OWNER_AUTHORIZATION_CONSUMED,
    OWNER_BOUND_READY_FOR_SINGLE_LAUNCH,
    SEALED_CANDIDATE_AWAITING_OWNER_AUTHORIZATION,
    FuturePreflightSealError,
    RetainedPreparationSealIdentity,
    observe_preparation_tree,
    preparation_root_identity,
    publish_future_preflight_seal,
    validate_future_preflight_seal,
)
from admissible.capsule.owner_authorization import (
    OWNER_DIGEST_CONSTRUCTION,
    OWNER_PHRASE_DESCRIPTOR_ENV,
    OwnerAuthorizationError,
    OwnerAuthorizationPayload,
    classify_local_chatgpt_login,
    owner_authorization_digest,
    read_owner_phrase_from_descriptor,
)
from admissible.capsule.owner_authority import (
    BROKER_PROTOCOL_VERSION,
    EXTERNAL_OWNER_DIGEST_CONSTRUCTION,
    OwnerAuthorityBroker,
    OwnerAuthorityBrokerClient,
    OwnerAuthorityError,
    OwnerAuthorityInstallation,
    SignedOwnerAuthorizationReceipt,
    attest_production_installation,
    describe_state_machine,
    installation_plan,
    production_installation_is_present,
    production_layout,
    render_installation_plan,
    verify_signed_receipt,
)
from admissible.capsule.owner_authority.gate import (
    revalidate_signed_owner_authority,
)
from admissible.capsule.docker_controller import (
    CapsuleExecutionAuthority,
    ControllerCleanupEvidence,
    DockerCapsuleController,
    DockerCapsuleLimits,
    DurableControllerAuthority,
)
from admissible.capsule.host_codex_backend import (
    CODEX_APP_SERVER_PROTOCOL_VERSION,
    DYNAMIC_TOOL_NAMESPACE,
    AppServerConnection,
    AppServerConnectionFactory,
    BwrapCodexConnectionFactory,
    BoundaryCodexConnectionFactory,
    HostCodexAppServerCapsuleBackend,
    NonProductionWitnessMode,
    OwnerAuthorityWitness,
    ProductionOwnerAuthorityWitness,
    SyntheticOwnerAuthorityWitness,
    ScriptedCodexAppServerConnection,
    ScriptedCodexConnectionFactory,
    dynamic_tools_grammar,
)
from admissible.capsule.boundary_authority import (
    DestinationManifest,
    OSBoundaryAuthority,
    SealedDestinationPinManifest,
)
from admissible.capsule.boundary_launcher import (
    BoundaryLauncher,
    BoundaryLifecycleEvidence,
    CodexConfinementLaunchPolicy,
    ControllerConfinementLaunchPolicy,
)
from admissible.capsule.authentication_broker import AuthenticationBrokerProcess
from admissible.capsule.capsule_broker import (
    CapsuleBrokerAuthority,
    CapsuleBrokerClient,
    CapsuleBrokerConfig,
    CapsuleBrokerProcess,
)
from admissible.capsule.egress_relay import (
    EgressBudgets,
    PreventiveEgressRelay,
    resolve_and_seal,
)
from admissible.capsule.host_control import (
    AuthenticationBoundary,
    AuthenticatedControlAuthority,
    HostControlBwrapPolicy,
    PendingAuthenticationBoundary,
    SyntheticAuthenticationBoundary,
)
from admissible.capsule.execution_authority import (
    BackendExecutionAuthority,
    ExecutableFileIdentity,
)
from admissible.capsule.models import (
    ByteTreeObservation,
    CleanupResult,
    ExecutionTruth,
    ObservedEntry,
    ProcessResult,
    ProviderCompletionClaim,
    ProviderOutput,
    ProviderTerminalClassification,
    TransportResult,
    WorkspaceReference,
)
from admissible.capsule.reducer import IllegalTransition, reduce
from admissible.capsule.session_store import (
    DurableCapsuleSessionStore,
    DurableToolRequest,
    DurableToolResult,
    ReconstructedCapsuleSession,
    SessionTerminalClassification,
    ToolIdDisposition,
    ToolTerminalClassification,
)
from admissible.capsule.state import TERMINAL_PHASES, CapsuleSessionState, Phase, new_session_state
from admissible.capsule.verification import (
    BehavioralVerifierIdentity,
    BehaviorRefusalCode,
    BehaviorResult,
    ByteHashPair,
    CheckpointIdentity,
    CheckpointRefusalCode,
    CheckpointResult,
    CommandCapture,
    IndependentVerificationResult,
    VerificationCopy,
    require_independent_copies,
)

__all__ = [
    "CANARY_ALLOW_PROVIDER_MODEL_FALLBACK",
    "CANARY_CONFIGURED_MODEL",
    "CANARY_CONFIGURED_REASONING_EFFORT",
    "CANARY_EXACT_AUTHORITY",
    "CANARY_PINNED_CODEX_SHA256",
    "CANARY_PINNED_CODEX_VERSION",
    "CANARY_PROTOCOL_SCHEMA_IDENTITY",
    "CANARY_TXT_BYTES",
    "CodexModelAuthority",
    "ExactMaterialRecord",
    "CANDIDATE_WITNESS_TRUST_STATE",
    "CandidateEvidenceBundle",
    "CandidateSerializationWitnessPack",
    "FUTURE_PREFLIGHT_MANIFEST_PATH",
    "FUTURE_PREFLIGHT_SEAL_PATH",
    "OWNER_AUTHORIZATION_CONSUMED",
    "OWNER_BOUND_READY_FOR_SINGLE_LAUNCH",
    "OWNER_DIGEST_CONSTRUCTION",
    "OWNER_PHRASE_DESCRIPTOR_ENV",
    "SEALED_CANDIDATE_AWAITING_OWNER_AUTHORIZATION",
    "NonProductionWitnessMode",
    "BROKER_PROTOCOL_VERSION",
    "EXTERNAL_OWNER_DIGEST_CONSTRUCTION",
    "OwnerAuthorityBroker",
    "OwnerAuthorityBrokerClient",
    "OwnerAuthorityError",
    "OwnerAuthorityInstallation",
    "OwnerAuthorityWitness",
    "OwnerAuthorizationError",
    "OwnerAuthorizationPayload",
    "ProductionOwnerAuthorityWitness",
    "SignedOwnerAuthorizationReceipt",
    "SyntheticOwnerAuthorityWitness",
    "attest_production_installation",
    "describe_state_machine",
    "installation_plan",
    "production_installation_is_present",
    "production_layout",
    "render_installation_plan",
    "revalidate_signed_owner_authority",
    "verify_signed_receipt",
    "RetainedPreparationSealIdentity",
    "classify_local_chatgpt_login",
    "observe_preparation_tree",
    "owner_authorization_digest",
    "preparation_root_identity",
    "read_owner_phrase_from_descriptor",
    "FuturePreflightSealError",
    "MODEL_CONFIGURATION_CHANNEL",
    "ModelBindingPolicy",
    "ModelConfigurationError",
    "SerializationWitnessError",
    "SerializationWitnessRecord",
    "CandidateSerializationWitnessStore",
    "CandidateSerializationWitnessReceipt",
    "canary_model_authority",
    "canary_model_binding_policy",
    "ephemeral_config_bytes",
    "evaluate_serialization_witness",
    "extract_witness_record",
    "publish_future_preflight_seal",
    "serialization_witness_identity",
    "trusted_witness_verifier_identity",
    "validate_effective_thread_configuration",
    "validate_future_preflight_seal",
    "witness_capture_policy",
    "AcceptedBlob",
    "AcceptedMaterialIdentity",
    "AdmissibleFinalizer",
    "AppServerConnection",
    "AppServerConnectionFactory",
    "AuthenticationBoundary",
    "AuthenticatedControlAuthority",
    "BackendExecutionAuthority",
    "BehavioralVerifierIdentity",
    "BehaviorRefusalCode",
    "BehaviorResult",
    "BehaviorVerified",
    "ByteHashPair",
    "ByteTreeObservation",
    "BwrapCodexConnectionFactory",
    "BoundaryCodexConnectionFactory",
    "BoundaryLauncher",
    "BoundaryLifecycleEvidence",
    "CodexConfinementLaunchPolicy",
    "ControllerConfinementLaunchPolicy",
    "CODEX_APP_SERVER_PROTOCOL_VERSION",
    "CanonicalIntake",
    "CapsuleAuthority",
    "CapsuleBrokerAuthority",
    "CapsuleBrokerClient",
    "CapsuleBrokerConfig",
    "CapsuleBrokerProcess",
    "CapsuleBackend",
    "CapsuleEvent",
    "CapsuleExecutionAuthority",
    "CapsuleExecutionStarted",
    "CapsuleSessionState",
    "CapsuleTerminalClassification",
    "CheckpointIdentity",
    "CheckpointRefusalCode",
    "CheckpointResult",
    "CheckpointVerificationStarted",
    "CheckpointVerified",
    "CleanupResult",
    "CommandCapture",
    "ControllerCleanupEvidence",
    "DYNAMIC_TOOL_NAMESPACE",
    "DockerCapsuleController",
    "DockerCapsuleLimits",
    "DestinationManifest",
    "DurableCapsuleSessionStore",
    "DurabilityReceipt",
    "DurableEvidenceStoreAuthority",
    "DurableFinalizationEvidenceStore",
    "DurableControllerAuthority",
    "DurableToolRequest",
    "DurableToolResult",
    "ExecutionTruth",
    "EgressBudgets",
    "ExecutableFileIdentity",
    "FailureCode",
    "FinalizationCompleted",
    "FinalizationEvidence",
    "FinalizationOutcome",
    "FinalizationResult",
    "FinalizationStarted",
    "FinalizerAuthority",
    "FinalizerOperationalError",
    "FinalizerPreconditionError",
    "FROZEN_IDENTITY",
    "HostCodexAppServerCapsuleBackend",
    "HostControlBwrapPolicy",
    "IllegalTransition",
    "IndependentVerificationResult",
    "IntakeAuthority",
    "IntakeEvaluated",
    "IntakeEvidence",
    "IntakeFileRecord",
    "IntakePublicationState",
    "IntakeStarted",
    "NEON_RELAY_AUTHORITY",
    "ObservedEntry",
    "OSBoundaryAuthority",
    "Phase",
    "PendingAuthenticationBoundary",
    "PreventiveEgressRelay",
    "ProcessResult",
    "ProviderCompletionClaim",
    "ProviderOutput",
    "ProviderOutputFrozen",
    "ProviderTerminalClassification",
    "RefusalReason",
    "RejectionCode",
    "PreparedFinalization",
    "ReconstructedCapsuleSession",
    "SessionFailed",
    "SessionTerminalClassification",
    "SealedDestinationPinManifest",
    "ScriptedCodexAppServerConnection",
    "ScriptedCodexConnectionFactory",
    "SyntheticAuthenticationBoundary",
    "AuthenticationBrokerProcess",
    "TERMINAL_PHASES",
    "TransportResult",
    "ToolIdDisposition",
    "ToolTerminalClassification",
    "VerificationCopy",
    "WorkspaceReference",
    "initialize_disposable_repository",
    "new_session_state",
    "path_policy_reasons",
    "reduce",
    "resolve_and_seal",
    "require_independent_copies",
    "validate_and_copy",
    "dynamic_tools_grammar",
]
