"""Pure Milestone 1 executable architecture specification.

This namespace contains immutable data models, canonicalization, identity
binding, and parity checking only.  It deliberately has no model transport,
filesystem tool, subprocess executor, policy implementation, owner broker,
or provider integration.
"""

from .canonical import (
    CanonicalizationError,
    Fingerprint,
    NonCanonicalEncodingError,
    canonical_bytes,
    fingerprint,
    fingerprint_bytes,
    parse_canonical_json,
    strict_json_loads,
)
from .comparison import ParityRefused, ParityReport, check_parity, require_parity
from .identities import IdentityReference, RunIdentity, SessionIdentity
from .specification import (
    AllowedConditionDifferences,
    BudgetLimits,
    BudgetState,
    BudgetUsage,
    CanonicalProposal,
    CausalPredecessor,
    ClockObservation,
    ComparativeManifest,
    ConditionConfiguration,
    EffectReceipt,
    EffectReservation,
    EvaluatorSpecification,
    ExperimentSpecification,
    HumanInterventionRecord,
    ModeDecision,
    TerminalManifest,
    canonical_object_bytes,
    derive_evaluator_identity,
    derive_tool_grammar_identity,
    validate_unique_proposal_ids,
)
from .schemas import (
    RECEIPT_STATE_MATRIX,
    TERMINAL_STATE_MATRIX,
    receipt_process_exit_policy,
    receipt_reconciliation_required,
    receipt_state_rule,
)
from .tool_schemas import (
    ListFilesRequest,
    ListFilesResult,
    ReadFileRequest,
    ReadFileResult,
    RunCommandRequest,
    RunCommandResult,
    ToolGrammarEntry,
    ToolGrammarSpecification,
    ToolRequest,
    ToolResult,
    WriteFileRequest,
    WriteFileResult,
    tool_request_from_dict,
    tool_result_from_dict,
    written_content_fingerprint,
)

__all__ = [
    "AllowedConditionDifferences",
    "BudgetLimits",
    "BudgetState",
    "BudgetUsage",
    "CanonicalProposal",
    "CanonicalizationError",
    "CausalPredecessor",
    "ClockObservation",
    "ComparativeManifest",
    "ConditionConfiguration",
    "EffectReceipt",
    "EffectReservation",
    "EvaluatorSpecification",
    "ExperimentSpecification",
    "Fingerprint",
    "HumanInterventionRecord",
    "IdentityReference",
    "ModeDecision",
    "NonCanonicalEncodingError",
    "ParityRefused",
    "ParityReport",
    "RunIdentity",
    "RunCommandRequest",
    "RunCommandResult",
    "SessionIdentity",
    "TerminalManifest",
    "ToolGrammarEntry",
    "ToolGrammarSpecification",
    "ToolRequest",
    "ToolResult",
    "ListFilesRequest",
    "ListFilesResult",
    "ReadFileRequest",
    "ReadFileResult",
    "WriteFileRequest",
    "WriteFileResult",
    "RECEIPT_STATE_MATRIX",
    "TERMINAL_STATE_MATRIX",
    "canonical_bytes",
    "canonical_object_bytes",
    "check_parity",
    "derive_evaluator_identity",
    "derive_tool_grammar_identity",
    "fingerprint",
    "fingerprint_bytes",
    "parse_canonical_json",
    "receipt_process_exit_policy",
    "receipt_reconciliation_required",
    "receipt_state_rule",
    "require_parity",
    "strict_json_loads",
    "tool_request_from_dict",
    "tool_result_from_dict",
    "validate_unique_proposal_ids",
    "written_content_fingerprint",
]
