"""The paired-runner specification (M1) and shared effect substrate (M2).

Milestone 1 contributes immutable data models, canonicalization, identity
binding, and parity checking.  Milestone 2 adds one provider-free physical
substrate: durable publication, workspace confinement, the four tool
implementations, bounded process supervision, typed observations, and the
run/effect ledger with crash-safe reconciliation.  The second critical-repair
pass adds the capsule's syscall boundary and byte identity, per-command resource
containment, a non-executing Git observer, and a crash-classifiable durable event
index the effect ledger is derived from.  The third critical-repair pass replaces
the live writable workspace bind with a private execution view and trusted
export, verifies cgroup membership before command execution, and binds capsule
runtime identity through open descriptors.

The namespace still has no model transport, multi-session orchestration, policy
implementation, owner broker, authority, evaluator engine, or provider
integration.
"""

from .canonical import (
    CanonicalizationError,
    Fingerprint,
    NonCanonicalEncodingError,
    canonical_bytes,
    fingerprint,
    fingerprint_bytes,
    parse_canonical_json,
    strict_json_loads,
)
from .comparison import ParityRefused, ParityReport, check_parity, require_parity
from .durable_store import (
    FAULT_POINTS,
    CorruptDurableObject,
    DurableObjectStore,
    FaultInjector,
    InjectedFault,
    PublicationConflict,
)
from .capsule_identity import (
    CapsuleIdentityRefused,
    CapsuleRuntimeManifest,
    build_runtime_manifest,
    package_source_identity,
)
from .capsule_seccomp import SeccompUnavailable, build_program, describe as describe_seccomp
from .effect_ledger import EffectLedgerEntry, RunEffectLedger
from .effects import (
    AmbiguousEffectRefused,
    ConfigurationRefused,
    EffectExecutionOutcome,
    RunIndexRecovery,
    SharedEffectSubstrate,
    WorkspaceBinding,
    WorkspaceFailure,
    WorkspaceIpcEndpointRefused,
    WorkspaceRefusal,
    observe_filesystem,
    observe_git,
    reconcile_effect,
    recover_run_index,
    require_no_workspace_ipc_endpoints,
    scan_workspace_ipc_endpoints,
)
from .git_observer import GitObservationRefused, observe_repository
from .resource_limits import (
    CONTAINMENT_MECHANISMS,
    CgroupDelegation,
    ResourceBounds,
    probe_cgroup_delegation,
)
from .run_index import (
    DurableRunIndex,
    EVENT_KINDS,
    INDEX_OUTCOMES,
    RunIndexAnchor,
    RunIndexBroken,
    RunIndexEvent,
    RunIndexState,
)
from .sandbox import (
    CapsuleReadiness,
    CapsuleSpecification,
    SandboxUnavailable,
    probe_capsule_readiness,
)
from .observation import (
    M2_OBSERVATION_SCHEMAS,
    PUBLICATION_STATES,
    RECONCILIATION_CLASSIFICATIONS,
    TERMINAL_LEDGER_FINGERPRINT_DOMAINS,
    EffectReconciliationReport,
    FilesystemObservation,
    GitObservation,
    LifecycleRecord,
    ObservationError,
    ProcessObservation,
    PublicationReceipt,
    ResourceObservation,
    StreamObservation,
    observation_from_dict,
)
from .process_supervision import (
    CancellationToken,
    SupervisedProcessResult,
    controller_memory_bound,
    supervise_command,
)
from .identities import IdentityReference, RunIdentity, SessionIdentity
from .specification import (
    AllowedConditionDifferences,
    BudgetLimits,
    BudgetState,
    BudgetUsage,
    CanonicalProposal,
    CausalPredecessor,
    ClockObservation,
    ComparativeManifest,
    ConditionConfiguration,
    EffectReceipt,
    EffectReservation,
    EvaluatorSpecification,
    ExperimentSpecification,
    HumanInterventionRecord,
    ModeDecision,
    TerminalManifest,
    canonical_object_bytes,
    derive_evaluator_identity,
    derive_tool_grammar_identity,
    validate_unique_proposal_ids,
)
from .schemas import (
    RECEIPT_STATE_MATRIX,
    TERMINAL_STATE_MATRIX,
    receipt_process_exit_policy,
    receipt_reconciliation_required,
    receipt_state_rule,
)
from .tool_schemas import (
    ListFilesRequest,
    ListFilesResult,
    ReadFileRequest,
    ReadFileResult,
    RunCommandRequest,
    RunCommandResult,
    ToolGrammarEntry,
    ToolGrammarSpecification,
    ToolRequest,
    ToolResult,
    WriteFileRequest,
    WriteFileResult,
    tool_request_from_dict,
    tool_result_from_dict,
    written_content_fingerprint,
)

__all__ = [
    "AllowedConditionDifferences",
    "AmbiguousEffectRefused",
    "CONTAINMENT_MECHANISMS",
    "CancellationToken",
    "CapsuleIdentityRefused",
    "CapsuleReadiness",
    "CapsuleRuntimeManifest",
    "CapsuleSpecification",
    "CgroupDelegation",
    "ConfigurationRefused",
    "DurableRunIndex",
    "EVENT_KINDS",
    "GitObservationRefused",
    "INDEX_OUTCOMES",
    "ResourceBounds",
    "RunIndexAnchor",
    "RunIndexBroken",
    "RunIndexEvent",
    "RunIndexRecovery",
    "RunIndexState",
    "SandboxUnavailable",
    "SeccompUnavailable",
    "WorkspaceIpcEndpointRefused",
    "build_program",
    "build_runtime_manifest",
    "describe_seccomp",
    "observe_repository",
    "package_source_identity",
    "probe_capsule_readiness",
    "probe_cgroup_delegation",
    "recover_run_index",
    "require_no_workspace_ipc_endpoints",
    "scan_workspace_ipc_endpoints",
    "CorruptDurableObject",
    "DurableObjectStore",
    "EffectExecutionOutcome",
    "EffectLedgerEntry",
    "EffectReconciliationReport",
    "FAULT_POINTS",
    "FaultInjector",
    "FilesystemObservation",
    "GitObservation",
    "InjectedFault",
    "LifecycleRecord",
    "M2_OBSERVATION_SCHEMAS",
    "ObservationError",
    "PUBLICATION_STATES",
    "ProcessObservation",
    "PublicationConflict",
    "PublicationReceipt",
    "RECONCILIATION_CLASSIFICATIONS",
    "ResourceObservation",
    "RunEffectLedger",
    "SharedEffectSubstrate",
    "StreamObservation",
    "SupervisedProcessResult",
    "TERMINAL_LEDGER_FINGERPRINT_DOMAINS",
    "WorkspaceBinding",
    "WorkspaceFailure",
    "WorkspaceRefusal",
    "controller_memory_bound",
    "observation_from_dict",
    "observe_filesystem",
    "observe_git",
    "reconcile_effect",
    "supervise_command",
    "BudgetLimits",
    "BudgetState",
    "BudgetUsage",
    "CanonicalProposal",
    "CanonicalizationError",
    "CausalPredecessor",
    "ClockObservation",
    "ComparativeManifest",
    "ConditionConfiguration",
    "EffectReceipt",
    "EffectReservation",
    "EvaluatorSpecification",
    "ExperimentSpecification",
    "Fingerprint",
    "HumanInterventionRecord",
    "IdentityReference",
    "ModeDecision",
    "NonCanonicalEncodingError",
    "ParityRefused",
    "ParityReport",
    "RunIdentity",
    "RunCommandRequest",
    "RunCommandResult",
    "SessionIdentity",
    "TerminalManifest",
    "ToolGrammarEntry",
    "ToolGrammarSpecification",
    "ToolRequest",
    "ToolResult",
    "ListFilesRequest",
    "ListFilesResult",
    "ReadFileRequest",
    "ReadFileResult",
    "WriteFileRequest",
    "WriteFileResult",
    "RECEIPT_STATE_MATRIX",
    "TERMINAL_STATE_MATRIX",
    "canonical_bytes",
    "canonical_object_bytes",
    "check_parity",
    "derive_evaluator_identity",
    "derive_tool_grammar_identity",
    "fingerprint",
    "fingerprint_bytes",
    "parse_canonical_json",
    "receipt_process_exit_policy",
    "receipt_reconciliation_required",
    "receipt_state_rule",
    "require_parity",
    "strict_json_loads",
    "tool_request_from_dict",
    "tool_result_from_dict",
    "validate_unique_proposal_ids",
    "written_content_fingerprint",
]
